name: E2E

# based on https://docs.wavs.xyz/ & this repos README.md

on:
  pull_request:
  workflow_dispatch:

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DEBUGGING: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ubuntu packages
      run: sudo apt-get install bash make jq

    - uses: actions/setup-node@v4
      name: Install Node.js
      with:
        node-version: 21

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache Rust target
      uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/toolchains
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-wasm32-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-wasm32-

    - uses: cargo-bins/cargo-binstall@main
      name: Install cargo-binstall
      with:
        version: latest

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install rust wasm32-wasip2
      run: rustup target add wasm32-wasip2

    - name: Install wasi components
      run: |
        cargo binstall cargo-component warg-cli wkg --locked --no-confirm
        wkg config --default-registry wa.dev

    - name: Install forge deps
      run: make setup

    - name: build contracts
      run: forge build

    - name: wasi build and local exec
      run: |
        make wasi-build
        make wasi-exec

    # modified version of `make start-all`
    - name: Build the stack
      run: |
        cp .env.example .env
        anvil --host 0.0.0.0 &
        docker compose up -d

    - name: Run tests
      run: |
        make deploy-contracts
        sleep 1
        TRIGGER_EVENT="NewTrigger(bytes)" make deploy-service
        sleep 1
        COIN_MARKET_CAP_ID=1 make trigger-service
        sleep 1

    - name: Run show result
      run: make show-result

    - name: Stop the stack
      run: |
        killall anvil
        docker compose down
